[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[env]
PORT = "3000"
NODE_ENV = "production"
DATABASE_URL = "postgresql://postgres.swyvtuwkhgzlluzkwvhl:Amds2025@@aws-0-sa-east-1.pooler.supabase.com:6543/postgres"
